dist: trusty

addons:
  apt:
    packages:
      - srecord

before_install:
  # asxxxx
  - git clone https://github.com/mnaberez/asxxxx.git
  - make -C asxxxx/asxv5pxx/asxmak/linux/build all
  - export PATH=$PATH:$PWD/asxxxx/asxv5pxx/asxmak/linux/build

language: python

script:
  - make -C firmware
