dist: trusty

addons:
  apt:
    packages:
      - srecord

before_install:
  # asxxxx
  - wget -q -U travis http://6502.org/tools/asm/asxv5p31.zip
  - unzip -q asxv5p31.zip
  - make -C asxv5pxx/asxmak/linux/build all
  - export PATH=$PATH:$PWD/asxv5pxx/asxmak/linux/build

language: python

script:
  - make -C firmware
