name: Build the firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3

    - name: Install asxxxx
      run: |
        wget --no-verbose https://github.com/6502org/6502.org/raw/74f5d0c0f9b73d5e353bde7b3b25ea7f43b527a1/public/tools/asm/asxs5p50.zip
        unzip -q asxs5p50.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Install srecord
      run: |
        sudo apt-get install -y srecord

    - name: Build the firmware
      run: make -C firmware

    - name: 'Upload build artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
            firmware/out.bin
            firmware/out.lst
