name: Build the firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2

    - name: Install asxxxx
      run: |
        wget --no-verbose --content-disposition https://github.com/6502org/6502.org/blob/026b6de2a63caf97f54903c775c9a52edb12324e/public/tools/asm/asxv5p40_20210426.zip?raw=true
        unzip -q asxv5p40_20210426.zip
        make -C asxv5pxx/asxmak/linux/build all
        echo "$PWD/asxv5pxx/asxmak/linux/build" >> $GITHUB_PATH

    - name: Install srecord
      run: |
        sudo apt-get install -y srecord

    - name: Build the firmware
      run: make -C firmware
